### ISSUE TITLE
Depositing negative amount fails with unexpected error

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/plutus-use-cases#122]
Depositing negative amount causes contract fail with `InsufficientFunds` error.
Expected(?) result: transaction fails with  `NegativeValue`

Probably problem is here:
```
deposit :: GovParams -> Api.Deposit -> GovernanceContract ()
deposit params (Api.Deposit amnt) = do
  ...
  let ...
      xGovValue = Validation.xgovSingleton params.nft (coerce ownPkh) amnt
      ...
      tx = sconcat [
          Constraints.mustMintValue               xGovValue
        ...
        ]
 ...
```
It creates `Value` with negative amount and tries to burn xGOV tokens, but there are no tokens in the wallet yet. 
Not sure what need to be adjusted - contract logic or test case.

**Comment by zygomeb** [comment]
User cannot possess negative funds -- therefore the message is correct.
We check this assumption by delegating it to the blockchain's own assumptions

**Comment by mikekeke** [comment]
But there will be another error if user deposit positive amount first , and then deposit negative, and this time error will be ` NegativeValue`. It can be confusing.

**Comment by zygomeb** [comment]
Sure but it's pointless to introduce anything like that, this is a matter of UX and may be relegated to an error-out from the Contract monad but I'd delay that, or disregard it since this is meant not to be a finished product but an example. If someone comes in and modifies the code such that the security doesn't hold anymore, one may then think that the Contract check is an actual security guarantee.
Regardless I see no point in having clear error messages other than for the purpose of debugging, which this is not it.

**Comment by mikekeke** [comment]
Decided to cover both cases separately to kinda document contract behavior.
test cases added.
