### ISSUE TITLE
NFT: swap Plutus one-shot minting with custom one-shot minting contract 

### ISSUE THREAD

**Issue by cstml** [mlabs-haskell/plutus-use-cases#258]
Currently we are using IOHK contract to mint initial NFT and initialize app:
```haskell
mintContract
    :: forall w s e.
    ( AsCurrencyError e
    )
    => PubKeyHash
    -> [(TokenName, Integer)]
    -> Contract w s e OneShotCurrency
mintContract pk amounts = mapError (review _CurrencyError) $ do
    txOutRef <- getUnspentOutput
    utxos <- utxosAt (pubKeyHashAddress pk)
    let theCurrency = mkCurrency txOutRef amounts
        curVali     = curPolicy theCurrency
        lookups     = Constraints.mintingPolicy curVali
                        <> Constraints.unspentOutputs utxos
        mintTx      = Constraints.mustSpendPubKeyOutput txOutRef
                        <> Constraints.mustMintValue (mintedValue theCurrency)
    tx <- submitTxConstraintsWith @Scripts.Any lookups mintTx
    _ <- awaitTxConfirmed (getCardanoTxId tx)
    pure theCurrency
```
There are several issues with it now:

- [ ] `getUnspentOutput` fails with "Some outputs have Ada values that are too small....". Plutus update can solve it, see
[SCP-2880: Transaction outputs should contain a minimum of 2 Ada. input-output-hk/plutus-apps#76](https://github.com/input-output-hk/plutus-apps/pull/76). Or just use 1st utxo from `utxosAt`
- [ ] `utxos` acquired with `utxosAt` from `cardano-wallet` doesn't always contain `txOutRef` . Probable solution - `txOutFromRef` could be use instead of `utxosAt`
- [ ] `Constraints.mustSpendPubKeyOutput txOutRef` will cause error BalanceTxError "Public key inputs not supported" on PAB balance call. This is how [export of inputs works now](https://github.com/input-output-hk/plutus-apps/blob/ac3f39e1c4384ce44fdb8c321985ac447e85e411/plutus-contract/src/Plutus/Contract/Wallet.hs#L183-L194). Probable solution - create utxo at script address with `pubKeyContract` [as IOHK IntegrationTest.hs does](https://github.com/input-output-hk/plutus-apps/blob/main/plutus-pab/examples/ContractExample/IntegrationTest.hs#L38) and use that utxo to mint initial NFT

**Comment by mikekeke** [comment]
Currenlty used IOHK contract is this:
```
mintContract
    :: forall w s e.
    ( AsCurrencyError e
    )
    => PubKeyHash
    -> [(TokenName, Integer)]
    -> Contract w s e OneShotCurrency
mintContract pk amounts = mapError (review _CurrencyError) $ do
    txOutRef <- getUnspentOutput
    utxos <- utxosAt (pubKeyHashAddress pk)
    let theCurrency = mkCurrency txOutRef amounts
        curVali     = curPolicy theCurrency
        lookups     = Constraints.mintingPolicy curVali
                        <> Constraints.unspentOutputs utxos
        mintTx      = Constraints.mustSpendPubKeyOutput txOutRef
                        <> Constraints.mustMintValue (mintedValue theCurrency)
    tx <- submitTxConstraintsWith @Scripts.Any lookups mintTx
    _ <- awaitTxConfirmed (getCardanoTxId tx)
    pure theCurrency

```
There are several issues with it now:
- [ ] `getUnspentOutput` fails with `Some outputs have ada values that are too small...`. Plutus update can solve it, see https://github.com/input-output-hk/plutus-apps/pull/76

- [ ] `utxos` acquired with `utxosAt` doesn't always contain `txOutRef `. Probable solution could be use `txOutFromRef` instead of `utxosAt`

- [ ] `Constraints.mustSpendPubKeyOutput txOutRef` will cause error `BalanceTxError "Public key inputs not supported"` on PAB balance call. This is how [export of inputs works now](https://github.com/input-output-hk/plutus-apps/blob/ac3f39e1c4384ce44fdb8c321985ac447e85e411/plutus-contract/src/Plutus/Contract/Wallet.hs#L183-L194). Probable solution - create utxo at script address with `pubKeyContract` [as IOHK IntegrationTest.hs does](https://github.com/input-output-hk/plutus-apps/blob/ac3f39e1c4384ce44fdb8c321985ac447e85e411/plutus-pab/examples/ContractExample/IntegrationTest.hs#L38) and use that utxo to mint initial NFT

**Comment by mikekeke** [comment]
Current applied solution was to use `PubKey.pubKeyContract` to lock utxo at script address and then use that utxo as input to mint one-shot currencies.
